//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN_ProductRequis
    {
        public int RequisID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Category { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Price { get; set; }
        public string UnitType { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<int> RequisAmount { get; set; }
        public string RequisNote { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ImgProduct { get; set; }
        public string UserID { get; set; }
        public string Barcode { get; set; }
        public string Location { get; set; }
        public string RequisStatus { get; set; }
        public string RequisNumber { get; set; }
    }
}
