//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN_Product
    {
        public int ProductID { get; set; }
        public string Barcode { get; set; }
        public string ProductName { get; set; }
        public string Category { get; set; }
        public Nullable<int> Price { get; set; }
        public string UnitType { get; set; }
        public Nullable<int> MinValue { get; set; }
        public Nullable<int> MaxValue { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Vender { get; set; }
        public string ProductStatus { get; set; }
        public string ImgProduct { get; set; }
        public string SITES { get; set; }
        public string Place { get; set; }
    }
}
