//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN_Requisition
    {
        public int RequisID { get; set; }
        public string RequisName { get; set; }
        public string RequisPosition { get; set; }
        public string RequisDept { get; set; }
        public string RequisLocation { get; set; }
        public string RequisNote { get; set; }
        public Nullable<System.DateTime> RequisDate { get; set; }
        public string ApproveID { get; set; }
        public string ApproveName { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string RequisNumber { get; set; }
        public Nullable<int> TotalCost { get; set; }
        public string UserID { get; set; }
        public string SITES { get; set; }
        public string RequisStatus { get; set; }
        public string Signature { get; set; }
        public Nullable<System.DateTime> SignatureDate { get; set; }
    }
}
