//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN_Receiver
    {
        public int ReceiverID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> ReqAmount { get; set; }
        public Nullable<System.DateTime> ReqTime { get; set; }
        public string ESSUSR_Name { get; set; }
        public string EMP_EngName { get; set; }
        public string ReceiverSignature { get; set; }
        public string ReceiverESSUSR_Name { get; set; }
        public string ReceiverEMP_EngName { get; set; }
        public Nullable<System.DateTime> ReceiverTime { get; set; }
        public string SITES { get; set; }
        public string Status { get; set; }
        public Nullable<int> LocationProductID { get; set; }
        public string Category { get; set; }
    }
}
