//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN_StockCard
    {
        public int StockCardID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string UserID { get; set; }
        public string StockCardCategory { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Balance { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Price { get; set; }
        public string UnitType { get; set; }
        public string Category { get; set; }
        public string SITES { get; set; }
    }
}
