//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN_Sites
    {
        public int SITESID { get; set; }
        public string SITES { get; set; }
        public string ImgSITES { get; set; }
    }
}
