//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN_UnitType
    {
        public int UnitTypeID { get; set; }
        public string UnitTypeName { get; set; }
        public Nullable<int> UnitValue { get; set; }
    }
}
