//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryDBEntities : DbContext
    {
        public InventoryDBEntities()
            : base("name=InventoryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IN_Category> IN_Category { get; set; }
        public virtual DbSet<IN_Product> IN_Product { get; set; }
        public virtual DbSet<IN_UnitType> IN_UnitType { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<UserPermission> UserPermissions { get; set; }
        public virtual DbSet<IN_StockCard> IN_StockCard { get; set; }
        public virtual DbSet<IN_ProductRequis> IN_ProductRequis { get; set; }
        public virtual DbSet<IN_Location> IN_Location { get; set; }
        public virtual DbSet<IN_Sites> IN_Sites { get; set; }
        public virtual DbSet<IN_Requisition> IN_Requisition { get; set; }
        public virtual DbSet<IN_Package> IN_Package { get; set; }
        public virtual DbSet<IN_ProductLocation> IN_ProductLocation { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<V_RequisitionPACK> V_RequisitionPACK { get; set; }
        public virtual DbSet<IN_Receiver> IN_Receiver { get; set; }
    }
}
