//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public string ESSUSR_Name { get; set; }
        public string EMP_EngName { get; set; }
        public string EMP_Email { get; set; }
        public string Location { get; set; }
        public string Position { get; set; }
        public string SITES { get; set; }
        public string Status { get; set; }
        public string Permission { get; set; }
    }
}
